# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b038c3675fa03933ceb10bb899b91154234ba9e0d9bc72457b604fe6103d88d3883bd48c309f0b021503992061d20876562c84bbb326e2068afa841c29fa62c4

test:
  secret_key_base: 9da583a03d3606fb6ab68857e775e628823ff7f5713c36d86addf2745b0df25925cb96aec4f8c6d7ae445c71776a4661563b8c55874ea296a94cae6aa360e920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
